### ISSUE TITLE
Don't bail out on the first discovered error

### ISSUE THREAD

**Issue by wilzbach** [microservices/cli#369]
```yaml
omg: 1
actions:
  get:
    arguments:
      url:
        type: string
        required: true
        help: URL to get data from
  post:
    arguments:
      url:
        type: string
        required: true
        help: URL to post data to
      data:
        type: object
        required: true
        help: The data you want to post
```

Output:

```
1 error found:
  1. actions.get should have one of required property: 'http' 'format' 'rpc' or 'events'
```

Expected:

```
3 errors found:
  1. actions.get should have one of required property: 'http' 'format' 'rpc' or 'events'
  2. actions.post should have one of required property: 'http' 'format' 'rpc' or 'events'
  3. actions.post 'object' type requires 'properties'
```
